### ISSUE TITLE
Ability to mock request exception

### ISSUE THREAD

**Issue by esial** [speekha/httpmocker#62]
In version 1.6 interceptor is caching all exceptions throwed during creating `ResponseDescriptor` and return default response (404, page not found).

``` 
try {
    provider.loadResponse(request)?.let { response ->
        executeMockResponse(response, request, provider)
    }
} catch (e: Throwable) {
    logger.error("Scenario file could not be loaded", e)
    null
}
```
There is no possibility to mock any communication exception now. It would be nice to have such option back.

**Comment by speekha** [comment]
@esial 
The rationale for catching those exceptions is that HttpMocker should not modify the behavior of your app. So any exception due to HttpMocker should not make its way back up the stack to your app. In the next release, the 404 response has been completed with the exception message and stacktrace for debugging purposes.
On the other hand, the idea of simulating exceptions is interesting. Could you elaborate on your need? Would it be ok if I added a way to trigger exceptions based on an element defined in the scenario? For instance adding an error field to the scenario which would allow to throw the exception of your choice. At least, it would be explicit in the scenario and not an unwanted side-effect.

**Comment by esial** [comment]
@speekha 
Purpose of avoiding app behavior change sounds rightly, but as long as interceptor is using for test mock responses it would be nice to simulate any behavior of communication layer.
In my case interceptor is used only in espresso test. App has different handle of each communication exception. Throwing exception during creationg instance of `ResponseDescriptor` allowed me to simulate any of communication exceptions in test.
Idea of explicit declaration of exception seems to perfectly fit my expectations.

**Comment by speekha** [comment]
@esial 
I've prepared a PR with the new feature:
* dynamic mocks can trigger whatever exception they want, it won't be caught anymore
* static mocks can specify an error instead of a response for a certain request. An exception with the corresponding type and message will be thrown.
* when recording scenarios, if an exception occurs, it will be recorded in the scenario as well.
I might do a bit more clean up to my code before I merge it in develop (and probably publish a new 1.1.7). So in the meantime, let me know what you think about it. Does it answer all your concerns? Do you have any suggestion to improve it or fit your needs better?

**Comment by esial** [comment]
Great! I can't wait :)

**Comment by speekha** [comment]
@esial v1.1.7 has been published. Enjoy!
